- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600

- name: Install Base Packages (Debian)
  apt:
    name: "{{ base_packages }}"
    state: present
  
- name: Set timezone
  timezone:
    name: "{{ timezone }}"
